import type { Metadata } from "next";
import { Geist, Geist_Mono, Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/header";
import Footer from "@/components/common/footer";
import { Phone, Sparkle } from "lucide-react";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const rubik = Geist_Mono({
  variable: "--font-rubik",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${rubik.variable} antialiased`}
      >
        <Header />
        <main className="grid grid-cols-1 lg:justify-between lg:grid-cols-7">
          <section className="lg:col-span-5 relative ">{children}</section>

          <div className="payment-panel sticky top-0 self-start lg:col-span-2 hidden lg:flex flex-col items-center justify-center ">
            <div className="bg-white p-6 text-gray-900 shadow-lg w-full ">
              <p className="text-sm mb-2 text-black/60">
                After payment, send proof via WhatsApp with Your Full Name +
                Service Paid For.
              </p>
              <div className="flex items-center gap-2 mb-2">
                <div className="bg-blue-700 p-2 rounded-lg text-white">
                  <Sparkle size={20} />
                </div>
              </div>
              <h3 className="text-xl font-bold leading-tight mb-1">
                Pay & Start — Fast Checkout Interac e-Transfer (Canada Only)
              </h3>
              <Link
                href="mailto:holyonepathwaypartners@gmail.com"
                className="text-orange-600 text-sm font-medium mb-4 break-all"
              >
                ✉ holyonepathwaypartners@gmail.com
              </Link>

              <div className="text-sm font-medium mb-4">
                <p>
                  <span className="font-bold">Account Name:</span>
                  <br />
                  Holyone Pathway Partners
                </p>
                <p>
                  <span className="font-bold">Bank:</span> TD Bank
                </p>
                <p>
                  <span className="font-bold">Transit No:</span> 38572
                </p>
                <p>
                  <span className="font-bold">Institution No:</span> 004
                </p>
                <p>
                  <span className="font-bold">Account Number:</span> 5004123
                </p>
              </div>

              <div className="flex items-center gap-2 mb-2">
                <div className="bg-blue-700 p-2 rounded-lg text-white">
                  <Phone size={20} />
                </div>
              </div>
              <p className="text-sm font-bold mb-1">After Payment:</p>
              <p className="text-sm mb-4">
                Send screenshot to WhatsApp <br />
                <span className="font-medium">+1 548 325 8804</span>
              </p>

              <div className="flex items-center gap-2 mb-2">
                <div className="bg-blue-700 p-2 rounded-lg text-white">
                  <Sparkle size={20} />
                </div>
              </div>
              <p className="text-sm font-bold mb-1">
                International Wire Transfer
              </p>
              <div className="text-sm space-y-1">
                <p>
                  <span className="font-bold">Bank:</span> TD Canada Trust
                </p>
                <p>
                  <span className="font-bold">SWIFT/BIC:</span> TDOMGATTTOR
                </p>
                <p>
                  <span className="font-bold">Branch:</span> 190 Dundas St E,
                  Toronto, ON
                </p>
                <p>
                  <span className="font-bold">Wire Account:</span> 38575004123
                </p>
                <p>
                  <span className="font-bold">Account Name:</span> Holyone
                  Pathway Partners
                </p>
              </div>
            </div>

            <div className="bg-blue-700 text-white p-6  shadow-lg w-full ">
              {/* <h3 className="text-lg font-bold mb-3">Card Payment (Stripe)</h3> */}
              {/* <div className="flex gap-2 mb-4">
                <div className="bg-white text-blue-900 px-2 py-1 rounded font-bold text-xs">
                  VISA
                </div>
                <div className="bg-white text-red-600 px-2 py-1 rounded font-bold text-xs">
                  MasterCard
                </div>
                <div className="bg-black text-white px-2 py-1 rounded font-bold text-xs">
                  ApplePay
                </div>
              </div> */}

              <button className="w-full bg-red-600 hover:bg-red-700 text-white font-bold py-3 rounded mb-4 transition">
                Pay with Card
              </button>

              <p className="text-sm italic opacity-90">
                Micro-services begin same day. <br />
                Visa packages begin within 24–48 hours.
              </p>
            </div>
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
